### ISSUE TITLE
get_epi: EpiModel 2.0 and EpiModelHPC

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModelHPC#8]
The function `get_epi` now exists as a helper function in EpiModel 2 workflow, but is also an exported function of EpiModelHPC that overwrites the helper function. This will need to be changed going forward.
@smjenness

**Comment by smjenness** [comment]
Is this completed?

**Comment by andsv2** [comment]
`get_epi` removed from EpiModelHPC entirely. 
[Commit](https://github.com/statnet/EpiModelHPC/pull/9/commits/cc7338aa4947a5677115327d2ad029c119432fb7).
